### ISSUE TITLE
活跃度无法显示

### ISSUE THREAD

**Issue by yuan3old** [Tim-Fang/Dark-Aerfaying-Theme#5]
活跃度显示的像马赛克  
![image](https://user-images.githubusercontent.com/62503588/124247033-14585080-db54-11eb-8677-43d4686cfa2e.png)

**Comment by Tim-Fang** [comment]
远古bug请不要挖坟(恼

**Comment by threesix-aerfaying** [comment]
艹![image](https://user-images.githubusercontent.com/89340286/130434091-a75137ed-9730-4342-893c-bf4fa45ccbce.png)
（恼

**Comment by threesix-aerfaying** [comment]
往
```js
GM_addStyle(``)
```
里加
```css
.stat-graph_weeks_xL4mn img , .stat-graph_tips_3ptTC img {
  border: 1px solid #0d1117
}
```
(加哪里都行)，OK
